In [3]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
mouse_drug_data_csv = "data/mouse_drug_data.csv"
clinical_trial_data_csv = "data/clinicaltrial_data.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
mouse_drug_data = pd.read_csv(mouse_drug_data_csv)
clinical_trial_data = pd.read_csv(clinical_trial_data_csv)

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [4]:
# Combine the data into a single dataset
combined_data = pd.merge(clinical_trial_data, mouse_drug_data, how="left", on="Mouse ID")

# Display the data table for preview
combined_data.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites       Drug
0     b128          0                45.0                 0  Capomulin
1     f932          0                45.0                 0   Ketapril
2     g107          0                45.0                 0   Ketapril
3     a457          0                45.0                 0   Ketapril
4     c819          0                45.0                 0   Ketapril

## Tumor Response to Treatment

In [24]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 
mean_TV = combined_data.groupby(['Drug', 'Timepoint']).mean()['Tumor Volume (mm3)']

# Convert to DataFrame
mean_TV_df = pd.DataFrame({"Mean":mean_TV})

# Preview DataFrame
mean_TV_df

                          Mean
Drug      Timepoint
Capomulin 0          45.000000
          5          44.266086
          10         43.084291
          15         42.064317
          20         40.716325
...                        ...
Zoniferol 25         55.432935
          30         57.713531
          35         60.089372
          40         62.916692
          45         65.960888

[100 rows x 1 columns]

In [54]:
Capomulin_results = mean_TV_df[(mean_TV_df["Drug"] == "Capomulin")]
Ceftamin_results = merge_std_mean[(merge_std_mean["Drug"] == "Ceftamin")]
Infubinol_results = merge_std_mean[(merge_std_mean["Drug"] == "Infubinol")]
Ketapril_results = merge_std_mean[(merge_std_mean["Drug"] == "Ketapril")]
Naftisol_results = merge_std_mean[(merge_std_mean["Drug"] == "Naftisol")]
Placebo_results = merge_std_mean[(merge_std_mean["Drug"] == "Placebo")]
Propriva_results = merge_std_mean[(merge_std_mean["Drug"] == "Propriva")]
Ramicane_results = merge_std_mean[(merge_std_mean["Drug"] == "Ramicane")]
Stelasyn_results = merge_std_mean[(merge_std_mean["Drug"] == "Stelasyn")]
Zoniferol_results = merge_std_mean[(merge_std_mean["Drug"] == "Zoniferol")]

KeyError: 'Drug'

In [25]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint
StdErr_TV = combined_data.groupby(['Drug', 'Timepoint']).std()['Tumor Volume (mm3)']

# Convert to DataFrame
StdErr_TV_df = pd.DataFrame({"StdErr":StdErr_TV})

# Preview DataFrame
StdErr_TV_df

                       StdErr
Drug      Timepoint
Capomulin 0          0.000000
          5          2.242964
          10         3.513422
          15         4.108369
          20         4.362915
...                       ...
Zoniferol 25         2.410052
          30         3.098552
          35         3.297993
          40         3.736102
          45         3.755037

[100 rows x 1 columns]

        Drug  Timepoint  Tumor Volume (mm3)
0  Capomulin          0            0.000000
1  Capomulin          5            0.448593
2  Capomulin         10            0.702684
3  Capomulin         15            0.838617
4  Capomulin         20            0.909731

In [52]:
# Minor Data Munging to Re-Format the Data Frames
merge_std_mean = pd.merge(mean_TV_df, StdErr_TV_df, how="left", on=["Timepoint", "Drug"], right_index=False)

# Preview that Reformatting worked
merge_std_mean

                          Mean    StdErr
Timepoint Drug
0         Capomulin  45.000000  0.000000
5         Capomulin  44.266086  2.242964
10        Capomulin  43.084291  3.513422
15        Capomulin  42.064317  4.108369
20        Capomulin  40.716325  4.362915
...                        ...       ...
25        Zoniferol  55.432935  2.410052
30        Zoniferol  57.713531  3.098552
35        Zoniferol  60.089372  3.297993
40        Zoniferol  62.916692  3.736102
45        Zoniferol  65.960888  3.755037

[100 rows x 2 columns]

In [53]:
# Create data series by Drug names using conditionals
#Capomulin_results = df_merge_std_mean[(df_merge_std_mean["Drug"] == "Capomulin")]
Ceftamin_results = merge_std_mean[(merge_std_mean["Drug"] == "Ceftamin")]
Infubinol_results = merge_std_mean[(merge_std_mean["Drug"] == "Infubinol")]
Ketapril_results = merge_std_mean[(merge_std_mean["Drug"] == "Ketapril")]
Naftisol_results = merge_std_mean[(merge_std_mean["Drug"] == "Naftisol")]
Placebo_results = merge_std_mean[(merge_std_mean["Drug"] == "Placebo")]
Propriva_results = merge_std_mean[(merge_std_mean["Drug"] == "Propriva")]
Ramicane_results = merge_std_mean[(merge_std_mean["Drug"] == "Ramicane")]
Stelasyn_results = merge_std_mean[(merge_std_mean["Drug"] == "Stelasyn")]
Zoniferol_results = merge_std_mean[(merge_std_mean["Drug"] == "Zoniferol")]

# Group each by school name
#ninth_graders_scores = ninth_graders.groupby(["school_name"]).mean()["math_score"]
#tenth_graders_scores = tenth_graders.groupby(["school_name"]).mean()["math_score"]
#eleventh_graders_scores = eleventh_graders.groupby(["school_name"]).mean()["math_score"]
#twelfth_graders_scores = twelfth_graders.groupby(["school_name"]).mean()["math_score"]

# Combine series into single data frame
results_by_drug = pd.DataFrame({"Capomulin": Capomulin_results, "Ceftamin": Ceftamin_results})

# Minor data munging
#scores_by_grade = scores_by_grade[["9th", "10th", "11th", "12th"]]
#scores_by_grade.index.name = None

# Display the data frame
results_by_drug

KeyError: 'Drug'

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
5,44.266086,46.503051,47.062001,47.389175,46.796098,47.125589,47.248967,43.944859,47.527452,46.851818
10,43.084291,48.285125,49.403909,49.582269,48.694210,49.423329,49.101541,42.531957,49.463844,48.689881
15,42.064317,50.094055,51.296397,52.399974,50.933018,51.359742,51.067318,41.495061,51.529409,50.779059
20,40.716325,52.157049,53.197691,54.920935,53.644087,54.364417,53.346737,40.238325,54.067395,53.170334

In [ ]:
# Generate the Plot (with Error Bars)

# Save the Figure

In [ ]:
# Show the Figure
plt.show()

![Tumor Response to Treatment](../Images/treatment.png)

## Metastatic Response to Treatment

In [ ]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

                     Metastatic Sites
Drug      Timepoint
Capomulin 0                  0.000000
          5                  0.160000
          10                 0.320000
          15                 0.375000
          20                 0.652174

In [ ]:
# Store the Standard Error associated with Met. Sites Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

                     Metastatic Sites
Drug      Timepoint
Capomulin 0                  0.000000
          5                  0.074833
          10                 0.125433
          15                 0.132048
          20                 0.161621

In [ ]:
# Minor Data Munging to Re-Format the Data Frames

# Preview that Reformatting worked

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
5,44.266086,46.503051,47.062001,47.389175,46.796098,47.125589,47.248967,43.944859,47.527452,46.851818
10,43.084291,48.285125,49.403909,49.582269,48.694210,49.423329,49.101541,42.531957,49.463844,48.689881
15,42.064317,50.094055,51.296397,52.399974,50.933018,51.359742,51.067318,41.495061,51.529409,50.779059
20,40.716325,52.157049,53.197691,54.920935,53.644087,54.364417,53.346737,40.238325,54.067395,53.170334

In [ ]:
# Generate the Plot (with Error Bars)

# Save the Figure

# Show the Figure

![Metastatic Spread During Treatment](../Images/spread.png)

## Survival Rates

In [ ]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)

# Convert to DataFrame

# Preview DataFrame

        Drug  Timepoint  Mouse Count
0  Capomulin          0           25
1  Capomulin          5           25
2  Capomulin         10           25
3  Capomulin         15           24
4  Capomulin         20           23

In [ ]:
# Minor Data Munging to Re-Format the Data Frames

# Preview the Data Frame

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,25,25,25,25,25,25,26,25,26,25
5,25,21,25,23,23,24,25,25,25,24
10,25,20,21,22,21,24,23,24,23,22
15,24,19,21,19,21,20,17,24,23,21
20,23,18,20,19,20,19,17,23,21,17

In [ ]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/survival.png)

## Summary Bar Graph

In [ ]:
# Calculate the percent changes for each drug

# Display the data to confirm

Drug
Capomulin   -19.475303
Ceftamin     42.516492
Infubinol    46.123472
Ketapril     57.028795
Naftisol     53.923347
Placebo      51.297960
Propriva     47.241175
Ramicane    -22.320900
Stelasyn     52.085134
Zoniferol    46.579751
dtype: float64

In [ ]:
# Store all Relevant Percent Changes into a Tuple


# Splice the data between passing and failing drugs


# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
fig.show()

![Metastatic Spread During Treatment](../Images/change.png)